<?php
/**
 * OrderSslOrderAdditionalData
 *
 * PHP version 8.1
 *
 * @package  Layer7\Openprovider
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Layer7\Openprovider\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Layer7\Openprovider\ObjectSerializer;

/**
 * OrderSslOrderAdditionalData Class Doc Comment
 *
 * @package  Layer7\Openprovider
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class OrderSslOrderAdditionalData implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'orderSslOrderAdditionalData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'dns' => 'string',
        'dns_record' => 'string',
        'dns_value' => 'string',
        'domain' => 'string',
        'file_content' => 'string',
        'file_contents' => 'string',
        'file_location' => 'string',
        'file_name' => 'string',
        'md5' => 'string',
        'sha1' => 'string',
        'sha256' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'dns' => null,
        'dns_record' => null,
        'dns_value' => null,
        'domain' => null,
        'file_content' => null,
        'file_contents' => null,
        'file_location' => null,
        'file_name' => null,
        'md5' => null,
        'sha1' => null,
        'sha256' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'dns' => false,
        'dns_record' => false,
        'dns_value' => false,
        'domain' => false,
        'file_content' => false,
        'file_contents' => false,
        'file_location' => false,
        'file_name' => false,
        'md5' => false,
        'sha1' => false,
        'sha256' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'dns' => 'dns',
        'dns_record' => 'dns_record',
        'dns_value' => 'dns_value',
        'domain' => 'domain',
        'file_content' => 'file_content',
        'file_contents' => 'file_contents',
        'file_location' => 'file_location',
        'file_name' => 'file_name',
        'md5' => 'md5',
        'sha1' => 'sha1',
        'sha256' => 'sha256'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'dns' => 'setDns',
        'dns_record' => 'setDnsRecord',
        'dns_value' => 'setDnsValue',
        'domain' => 'setDomain',
        'file_content' => 'setFileContent',
        'file_contents' => 'setFileContents',
        'file_location' => 'setFileLocation',
        'file_name' => 'setFileName',
        'md5' => 'setMd5',
        'sha1' => 'setSha1',
        'sha256' => 'setSha256'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'dns' => 'getDns',
        'dns_record' => 'getDnsRecord',
        'dns_value' => 'getDnsValue',
        'domain' => 'getDomain',
        'file_content' => 'getFileContent',
        'file_contents' => 'getFileContents',
        'file_location' => 'getFileLocation',
        'file_name' => 'getFileName',
        'md5' => 'getMd5',
        'sha1' => 'getSha1',
        'sha256' => 'getSha256'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('dns', $data ?? [], null);
        $this->setIfExists('dns_record', $data ?? [], null);
        $this->setIfExists('dns_value', $data ?? [], null);
        $this->setIfExists('domain', $data ?? [], null);
        $this->setIfExists('file_content', $data ?? [], null);
        $this->setIfExists('file_contents', $data ?? [], null);
        $this->setIfExists('file_location', $data ?? [], null);
        $this->setIfExists('file_name', $data ?? [], null);
        $this->setIfExists('md5', $data ?? [], null);
        $this->setIfExists('sha1', $data ?? [], null);
        $this->setIfExists('sha256', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets dns
     *
     * @return string|null
     */
    public function getDns(): ?string
    {
        return $this->container['dns'];
    }

    /**
     * Sets dns
     *
     * @param string|null $dns dns
     *
     * @return $this
     */
    public function setDns(?string $dns): static
    {
        if (is_null($dns)) {
            throw new InvalidArgumentException('non-nullable dns cannot be null');
        }
        $this->container['dns'] = $dns;

        return $this;
    }

    /**
     * Gets dns_record
     *
     * @return string|null
     */
    public function getDnsRecord(): ?string
    {
        return $this->container['dns_record'];
    }

    /**
     * Sets dns_record
     *
     * @param string|null $dns_record dns_record
     *
     * @return $this
     */
    public function setDnsRecord(?string $dns_record): static
    {
        if (is_null($dns_record)) {
            throw new InvalidArgumentException('non-nullable dns_record cannot be null');
        }
        $this->container['dns_record'] = $dns_record;

        return $this;
    }

    /**
     * Gets dns_value
     *
     * @return string|null
     */
    public function getDnsValue(): ?string
    {
        return $this->container['dns_value'];
    }

    /**
     * Sets dns_value
     *
     * @param string|null $dns_value dns_value
     *
     * @return $this
     */
    public function setDnsValue(?string $dns_value): static
    {
        if (is_null($dns_value)) {
            throw new InvalidArgumentException('non-nullable dns_value cannot be null');
        }
        $this->container['dns_value'] = $dns_value;

        return $this;
    }

    /**
     * Gets domain
     *
     * @return string|null
     */
    public function getDomain(): ?string
    {
        return $this->container['domain'];
    }

    /**
     * Sets domain
     *
     * @param string|null $domain domain
     *
     * @return $this
     */
    public function setDomain(?string $domain): static
    {
        if (is_null($domain)) {
            throw new InvalidArgumentException('non-nullable domain cannot be null');
        }
        $this->container['domain'] = $domain;

        return $this;
    }

    /**
     * Gets file_content
     *
     * @return string|null
     */
    public function getFileContent(): ?string
    {
        return $this->container['file_content'];
    }

    /**
     * Sets file_content
     *
     * @param string|null $file_content file_content
     *
     * @return $this
     */
    public function setFileContent(?string $file_content): static
    {
        if (is_null($file_content)) {
            throw new InvalidArgumentException('non-nullable file_content cannot be null');
        }
        $this->container['file_content'] = $file_content;

        return $this;
    }

    /**
     * Gets file_contents
     *
     * @return string|null
     */
    public function getFileContents(): ?string
    {
        return $this->container['file_contents'];
    }

    /**
     * Sets file_contents
     *
     * @param string|null $file_contents file_contents
     *
     * @return $this
     */
    public function setFileContents(?string $file_contents): static
    {
        if (is_null($file_contents)) {
            throw new InvalidArgumentException('non-nullable file_contents cannot be null');
        }
        $this->container['file_contents'] = $file_contents;

        return $this;
    }

    /**
     * Gets file_location
     *
     * @return string|null
     */
    public function getFileLocation(): ?string
    {
        return $this->container['file_location'];
    }

    /**
     * Sets file_location
     *
     * @param string|null $file_location file_location
     *
     * @return $this
     */
    public function setFileLocation(?string $file_location): static
    {
        if (is_null($file_location)) {
            throw new InvalidArgumentException('non-nullable file_location cannot be null');
        }
        $this->container['file_location'] = $file_location;

        return $this;
    }

    /**
     * Gets file_name
     *
     * @return string|null
     */
    public function getFileName(): ?string
    {
        return $this->container['file_name'];
    }

    /**
     * Sets file_name
     *
     * @param string|null $file_name file_name
     *
     * @return $this
     */
    public function setFileName(?string $file_name): static
    {
        if (is_null($file_name)) {
            throw new InvalidArgumentException('non-nullable file_name cannot be null');
        }
        $this->container['file_name'] = $file_name;

        return $this;
    }

    /**
     * Gets md5
     *
     * @return string|null
     */
    public function getMd5(): ?string
    {
        return $this->container['md5'];
    }

    /**
     * Sets md5
     *
     * @param string|null $md5 md5
     *
     * @return $this
     */
    public function setMd5(?string $md5): static
    {
        if (is_null($md5)) {
            throw new InvalidArgumentException('non-nullable md5 cannot be null');
        }
        $this->container['md5'] = $md5;

        return $this;
    }

    /**
     * Gets sha1
     *
     * @return string|null
     */
    public function getSha1(): ?string
    {
        return $this->container['sha1'];
    }

    /**
     * Sets sha1
     *
     * @param string|null $sha1 sha1
     *
     * @return $this
     */
    public function setSha1(?string $sha1): static
    {
        if (is_null($sha1)) {
            throw new InvalidArgumentException('non-nullable sha1 cannot be null');
        }
        $this->container['sha1'] = $sha1;

        return $this;
    }

    /**
     * Gets sha256
     *
     * @return string|null
     */
    public function getSha256(): ?string
    {
        return $this->container['sha256'];
    }

    /**
     * Sets sha256
     *
     * @param string|null $sha256 sha256
     *
     * @return $this
     */
    public function setSha256(?string $sha256): static
    {
        if (is_null($sha256)) {
            throw new InvalidArgumentException('non-nullable sha256 cannot be null');
        }
        $this->container['sha256'] = $sha256;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


