<?php
/**
 * TldTld
 *
 * PHP version 8.1
 *
 * @package  Layer7\Openprovider
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * REST API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0-beta
 * @generated Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Layer7\Openprovider\Model;

use ArrayAccess;
use JsonSerializable;
use InvalidArgumentException;
use ReturnTypeWillChange;
use Layer7\Openprovider\ObjectSerializer;

/**
 * TldTld Class Doc Comment
 *
 * @package  Layer7\Openprovider
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements ArrayAccess<string, mixed>
 */
class TldTld implements ModelInterface, ArrayAccess, JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static string $openAPIModelName = 'tldTld';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var array<string, string>
      */
    protected static array $openAPITypes = [
        'admin_handle_supported' => 'bool',
        'billing_handle_enabled' => 'bool',
        'billing_handle_supported' => 'bool',
        'description' => '\Layer7\Openprovider\Model\TldDescription',
        'dnssec_algorithms' => 'int[]',
        'dnssec_allowed' => 'bool',
        'dnssec_digests_allowed' => 'bool',
        'dnssec_keys_allowed' => 'bool',
        'dnssec_max_records_amount' => 'int',
        'domicile_available' => 'bool',
        'is_auth_code_available' => 'bool',
        'is_auth_code_changeable' => 'bool',
        'is_auth_code_requested' => 'bool',
        'is_private_whois_allowed' => 'bool',
        'is_trade_auth_code_required' => 'string',
        'is_transfer_auth_code_required' => 'string',
        'level_prices' => '\Layer7\Openprovider\Model\TldLevelPrice[]',
        'max_period' => 'int',
        'min_period' => 'int',
        'name' => 'string',
        'owner_handle_supported' => 'bool',
        'prices' => '\Layer7\Openprovider\Model\TldPrices',
        'quarantine_period' => 'int',
        'reseller_handle_enabled' => 'bool',
        'reseller_handle_supported' => 'bool',
        'restrictions' => 'string[]',
        'status' => 'string',
        'supported_application_mode' => '\Layer7\Openprovider\Model\TldApplicationMode[]',
        'supported_idn_scripts' => '\Layer7\Openprovider\Model\TldIdnScript[]',
        'tech_handle_supported' => 'bool',
        'trade_available' => 'bool',
        'transfer_available' => 'bool',
        'usage_count' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var array<string, string|null>
      */
    protected static array $openAPIFormats = [
        'admin_handle_supported' => 'boolean',
        'billing_handle_enabled' => 'boolean',
        'billing_handle_supported' => 'boolean',
        'description' => null,
        'dnssec_algorithms' => 'int32',
        'dnssec_allowed' => 'boolean',
        'dnssec_digests_allowed' => 'boolean',
        'dnssec_keys_allowed' => 'boolean',
        'dnssec_max_records_amount' => 'int32',
        'domicile_available' => 'boolean',
        'is_auth_code_available' => 'boolean',
        'is_auth_code_changeable' => 'boolean',
        'is_auth_code_requested' => 'boolean',
        'is_private_whois_allowed' => 'boolean',
        'is_trade_auth_code_required' => null,
        'is_transfer_auth_code_required' => null,
        'level_prices' => null,
        'max_period' => 'int32',
        'min_period' => 'int32',
        'name' => null,
        'owner_handle_supported' => 'boolean',
        'prices' => null,
        'quarantine_period' => 'int32',
        'reseller_handle_enabled' => 'boolean',
        'reseller_handle_supported' => 'boolean',
        'restrictions' => null,
        'status' => null,
        'supported_application_mode' => null,
        'supported_idn_scripts' => null,
        'tech_handle_supported' => 'boolean',
        'trade_available' => 'boolean',
        'transfer_available' => 'boolean',
        'usage_count' => 'int32'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var array<string, bool>
      */
    protected static array $openAPINullables = [
        'admin_handle_supported' => false,
        'billing_handle_enabled' => false,
        'billing_handle_supported' => false,
        'description' => false,
        'dnssec_algorithms' => false,
        'dnssec_allowed' => false,
        'dnssec_digests_allowed' => false,
        'dnssec_keys_allowed' => false,
        'dnssec_max_records_amount' => false,
        'domicile_available' => false,
        'is_auth_code_available' => false,
        'is_auth_code_changeable' => false,
        'is_auth_code_requested' => false,
        'is_private_whois_allowed' => false,
        'is_trade_auth_code_required' => false,
        'is_transfer_auth_code_required' => false,
        'level_prices' => false,
        'max_period' => false,
        'min_period' => false,
        'name' => false,
        'owner_handle_supported' => false,
        'prices' => false,
        'quarantine_period' => false,
        'reseller_handle_enabled' => false,
        'reseller_handle_supported' => false,
        'restrictions' => false,
        'status' => false,
        'supported_application_mode' => false,
        'supported_idn_scripts' => false,
        'tech_handle_supported' => false,
        'trade_available' => false,
        'transfer_available' => false,
        'usage_count' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var array<string, bool>
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPITypes(): array
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array<string, string>
     */
    public static function openAPIFormats(): array
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array<string, bool>
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return array<string, bool>
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param array<string, bool> $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var array<string, string>
     */
    protected static array $attributeMap = [
        'admin_handle_supported' => 'admin_handle_supported',
        'billing_handle_enabled' => 'billing_handle_enabled',
        'billing_handle_supported' => 'billing_handle_supported',
        'description' => 'description',
        'dnssec_algorithms' => 'dnssec_algorithms',
        'dnssec_allowed' => 'dnssec_allowed',
        'dnssec_digests_allowed' => 'dnssec_digests_allowed',
        'dnssec_keys_allowed' => 'dnssec_keys_allowed',
        'dnssec_max_records_amount' => 'dnssec_max_records_amount',
        'domicile_available' => 'domicile_available',
        'is_auth_code_available' => 'is_auth_code_available',
        'is_auth_code_changeable' => 'is_auth_code_changeable',
        'is_auth_code_requested' => 'is_auth_code_requested',
        'is_private_whois_allowed' => 'is_private_whois_allowed',
        'is_trade_auth_code_required' => 'is_trade_auth_code_required',
        'is_transfer_auth_code_required' => 'is_transfer_auth_code_required',
        'level_prices' => 'level_prices',
        'max_period' => 'max_period',
        'min_period' => 'min_period',
        'name' => 'name',
        'owner_handle_supported' => 'owner_handle_supported',
        'prices' => 'prices',
        'quarantine_period' => 'quarantine_period',
        'reseller_handle_enabled' => 'reseller_handle_enabled',
        'reseller_handle_supported' => 'reseller_handle_supported',
        'restrictions' => 'restrictions',
        'status' => 'status',
        'supported_application_mode' => 'supported_application_mode',
        'supported_idn_scripts' => 'supported_idn_scripts',
        'tech_handle_supported' => 'tech_handle_supported',
        'trade_available' => 'trade_available',
        'transfer_available' => 'transfer_available',
        'usage_count' => 'usage_count'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var array<string, string>
     */
    protected static array $setters = [
        'admin_handle_supported' => 'setAdminHandleSupported',
        'billing_handle_enabled' => 'setBillingHandleEnabled',
        'billing_handle_supported' => 'setBillingHandleSupported',
        'description' => 'setDescription',
        'dnssec_algorithms' => 'setDnssecAlgorithms',
        'dnssec_allowed' => 'setDnssecAllowed',
        'dnssec_digests_allowed' => 'setDnssecDigestsAllowed',
        'dnssec_keys_allowed' => 'setDnssecKeysAllowed',
        'dnssec_max_records_amount' => 'setDnssecMaxRecordsAmount',
        'domicile_available' => 'setDomicileAvailable',
        'is_auth_code_available' => 'setIsAuthCodeAvailable',
        'is_auth_code_changeable' => 'setIsAuthCodeChangeable',
        'is_auth_code_requested' => 'setIsAuthCodeRequested',
        'is_private_whois_allowed' => 'setIsPrivateWhoisAllowed',
        'is_trade_auth_code_required' => 'setIsTradeAuthCodeRequired',
        'is_transfer_auth_code_required' => 'setIsTransferAuthCodeRequired',
        'level_prices' => 'setLevelPrices',
        'max_period' => 'setMaxPeriod',
        'min_period' => 'setMinPeriod',
        'name' => 'setName',
        'owner_handle_supported' => 'setOwnerHandleSupported',
        'prices' => 'setPrices',
        'quarantine_period' => 'setQuarantinePeriod',
        'reseller_handle_enabled' => 'setResellerHandleEnabled',
        'reseller_handle_supported' => 'setResellerHandleSupported',
        'restrictions' => 'setRestrictions',
        'status' => 'setStatus',
        'supported_application_mode' => 'setSupportedApplicationMode',
        'supported_idn_scripts' => 'setSupportedIdnScripts',
        'tech_handle_supported' => 'setTechHandleSupported',
        'trade_available' => 'setTradeAvailable',
        'transfer_available' => 'setTransferAvailable',
        'usage_count' => 'setUsageCount'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var array<string, string>
     */
    protected static array $getters = [
        'admin_handle_supported' => 'getAdminHandleSupported',
        'billing_handle_enabled' => 'getBillingHandleEnabled',
        'billing_handle_supported' => 'getBillingHandleSupported',
        'description' => 'getDescription',
        'dnssec_algorithms' => 'getDnssecAlgorithms',
        'dnssec_allowed' => 'getDnssecAllowed',
        'dnssec_digests_allowed' => 'getDnssecDigestsAllowed',
        'dnssec_keys_allowed' => 'getDnssecKeysAllowed',
        'dnssec_max_records_amount' => 'getDnssecMaxRecordsAmount',
        'domicile_available' => 'getDomicileAvailable',
        'is_auth_code_available' => 'getIsAuthCodeAvailable',
        'is_auth_code_changeable' => 'getIsAuthCodeChangeable',
        'is_auth_code_requested' => 'getIsAuthCodeRequested',
        'is_private_whois_allowed' => 'getIsPrivateWhoisAllowed',
        'is_trade_auth_code_required' => 'getIsTradeAuthCodeRequired',
        'is_transfer_auth_code_required' => 'getIsTransferAuthCodeRequired',
        'level_prices' => 'getLevelPrices',
        'max_period' => 'getMaxPeriod',
        'min_period' => 'getMinPeriod',
        'name' => 'getName',
        'owner_handle_supported' => 'getOwnerHandleSupported',
        'prices' => 'getPrices',
        'quarantine_period' => 'getQuarantinePeriod',
        'reseller_handle_enabled' => 'getResellerHandleEnabled',
        'reseller_handle_supported' => 'getResellerHandleSupported',
        'restrictions' => 'getRestrictions',
        'status' => 'getStatus',
        'supported_application_mode' => 'getSupportedApplicationMode',
        'supported_idn_scripts' => 'getSupportedIdnScripts',
        'tech_handle_supported' => 'getTechHandleSupported',
        'trade_available' => 'getTradeAvailable',
        'transfer_available' => 'getTransferAvailable',
        'usage_count' => 'getUsageCount'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array<string, string>
     */
    public static function attributeMap(): array
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array<string, string>
     */
    public static function setters(): array
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array<string, string>
     */
    public static function getters(): array
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName(): string
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var array
     */
    protected array $container = [];

    /**
     * Constructor
     *
     * @param array $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->setIfExists('admin_handle_supported', $data ?? [], null);
        $this->setIfExists('billing_handle_enabled', $data ?? [], null);
        $this->setIfExists('billing_handle_supported', $data ?? [], null);
        $this->setIfExists('description', $data ?? [], null);
        $this->setIfExists('dnssec_algorithms', $data ?? [], null);
        $this->setIfExists('dnssec_allowed', $data ?? [], null);
        $this->setIfExists('dnssec_digests_allowed', $data ?? [], null);
        $this->setIfExists('dnssec_keys_allowed', $data ?? [], null);
        $this->setIfExists('dnssec_max_records_amount', $data ?? [], null);
        $this->setIfExists('domicile_available', $data ?? [], null);
        $this->setIfExists('is_auth_code_available', $data ?? [], null);
        $this->setIfExists('is_auth_code_changeable', $data ?? [], null);
        $this->setIfExists('is_auth_code_requested', $data ?? [], null);
        $this->setIfExists('is_private_whois_allowed', $data ?? [], null);
        $this->setIfExists('is_trade_auth_code_required', $data ?? [], null);
        $this->setIfExists('is_transfer_auth_code_required', $data ?? [], null);
        $this->setIfExists('level_prices', $data ?? [], null);
        $this->setIfExists('max_period', $data ?? [], null);
        $this->setIfExists('min_period', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('owner_handle_supported', $data ?? [], null);
        $this->setIfExists('prices', $data ?? [], null);
        $this->setIfExists('quarantine_period', $data ?? [], null);
        $this->setIfExists('reseller_handle_enabled', $data ?? [], null);
        $this->setIfExists('reseller_handle_supported', $data ?? [], null);
        $this->setIfExists('restrictions', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('supported_application_mode', $data ?? [], null);
        $this->setIfExists('supported_idn_scripts', $data ?? [], null);
        $this->setIfExists('tech_handle_supported', $data ?? [], null);
        $this->setIfExists('trade_available', $data ?? [], null);
        $this->setIfExists('transfer_available', $data ?? [], null);
        $this->setIfExists('usage_count', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, mixed $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return string[] invalid properties with reasons
     */
    public function listInvalidProperties(): array
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid(): bool
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets admin_handle_supported
     *
     * @return bool|null
     */
    public function getAdminHandleSupported(): ?bool
    {
        return $this->container['admin_handle_supported'];
    }

    /**
     * Sets admin_handle_supported
     *
     * @param bool|null $admin_handle_supported admin_handle_supported
     *
     * @return $this
     */
    public function setAdminHandleSupported(?bool $admin_handle_supported): static
    {
        if (is_null($admin_handle_supported)) {
            throw new InvalidArgumentException('non-nullable admin_handle_supported cannot be null');
        }
        $this->container['admin_handle_supported'] = $admin_handle_supported;

        return $this;
    }

    /**
     * Gets billing_handle_enabled
     *
     * @return bool|null
     */
    public function getBillingHandleEnabled(): ?bool
    {
        return $this->container['billing_handle_enabled'];
    }

    /**
     * Sets billing_handle_enabled
     *
     * @param bool|null $billing_handle_enabled billing_handle_enabled
     *
     * @return $this
     */
    public function setBillingHandleEnabled(?bool $billing_handle_enabled): static
    {
        if (is_null($billing_handle_enabled)) {
            throw new InvalidArgumentException('non-nullable billing_handle_enabled cannot be null');
        }
        $this->container['billing_handle_enabled'] = $billing_handle_enabled;

        return $this;
    }

    /**
     * Gets billing_handle_supported
     *
     * @return bool|null
     */
    public function getBillingHandleSupported(): ?bool
    {
        return $this->container['billing_handle_supported'];
    }

    /**
     * Sets billing_handle_supported
     *
     * @param bool|null $billing_handle_supported billing_handle_supported
     *
     * @return $this
     */
    public function setBillingHandleSupported(?bool $billing_handle_supported): static
    {
        if (is_null($billing_handle_supported)) {
            throw new InvalidArgumentException('non-nullable billing_handle_supported cannot be null');
        }
        $this->container['billing_handle_supported'] = $billing_handle_supported;

        return $this;
    }

    /**
     * Gets description
     *
     * @return \Layer7\Openprovider\Model\TldDescription|null
     */
    public function getDescription(): ?\Layer7\Openprovider\Model\TldDescription
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param \Layer7\Openprovider\Model\TldDescription|null $description description
     *
     * @return $this
     */
    public function setDescription(?\Layer7\Openprovider\Model\TldDescription $description): static
    {
        if (is_null($description)) {
            throw new InvalidArgumentException('non-nullable description cannot be null');
        }
        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets dnssec_algorithms
     *
     * @return int[]|null
     */
    public function getDnssecAlgorithms(): ?array
    {
        return $this->container['dnssec_algorithms'];
    }

    /**
     * Sets dnssec_algorithms
     *
     * @param int[]|null $dnssec_algorithms dnssec_algorithms
     *
     * @return $this
     */
    public function setDnssecAlgorithms(?array $dnssec_algorithms): static
    {
        if (is_null($dnssec_algorithms)) {
            throw new InvalidArgumentException('non-nullable dnssec_algorithms cannot be null');
        }
        $this->container['dnssec_algorithms'] = $dnssec_algorithms;

        return $this;
    }

    /**
     * Gets dnssec_allowed
     *
     * @return bool|null
     */
    public function getDnssecAllowed(): ?bool
    {
        return $this->container['dnssec_allowed'];
    }

    /**
     * Sets dnssec_allowed
     *
     * @param bool|null $dnssec_allowed dnssec_allowed
     *
     * @return $this
     */
    public function setDnssecAllowed(?bool $dnssec_allowed): static
    {
        if (is_null($dnssec_allowed)) {
            throw new InvalidArgumentException('non-nullable dnssec_allowed cannot be null');
        }
        $this->container['dnssec_allowed'] = $dnssec_allowed;

        return $this;
    }

    /**
     * Gets dnssec_digests_allowed
     *
     * @return bool|null
     */
    public function getDnssecDigestsAllowed(): ?bool
    {
        return $this->container['dnssec_digests_allowed'];
    }

    /**
     * Sets dnssec_digests_allowed
     *
     * @param bool|null $dnssec_digests_allowed dnssec_digests_allowed
     *
     * @return $this
     */
    public function setDnssecDigestsAllowed(?bool $dnssec_digests_allowed): static
    {
        if (is_null($dnssec_digests_allowed)) {
            throw new InvalidArgumentException('non-nullable dnssec_digests_allowed cannot be null');
        }
        $this->container['dnssec_digests_allowed'] = $dnssec_digests_allowed;

        return $this;
    }

    /**
     * Gets dnssec_keys_allowed
     *
     * @return bool|null
     */
    public function getDnssecKeysAllowed(): ?bool
    {
        return $this->container['dnssec_keys_allowed'];
    }

    /**
     * Sets dnssec_keys_allowed
     *
     * @param bool|null $dnssec_keys_allowed dnssec_keys_allowed
     *
     * @return $this
     */
    public function setDnssecKeysAllowed(?bool $dnssec_keys_allowed): static
    {
        if (is_null($dnssec_keys_allowed)) {
            throw new InvalidArgumentException('non-nullable dnssec_keys_allowed cannot be null');
        }
        $this->container['dnssec_keys_allowed'] = $dnssec_keys_allowed;

        return $this;
    }

    /**
     * Gets dnssec_max_records_amount
     *
     * @return int|null
     */
    public function getDnssecMaxRecordsAmount(): ?int
    {
        return $this->container['dnssec_max_records_amount'];
    }

    /**
     * Sets dnssec_max_records_amount
     *
     * @param int|null $dnssec_max_records_amount dnssec_max_records_amount
     *
     * @return $this
     */
    public function setDnssecMaxRecordsAmount(?int $dnssec_max_records_amount): static
    {
        if (is_null($dnssec_max_records_amount)) {
            throw new InvalidArgumentException('non-nullable dnssec_max_records_amount cannot be null');
        }
        $this->container['dnssec_max_records_amount'] = $dnssec_max_records_amount;

        return $this;
    }

    /**
     * Gets domicile_available
     *
     * @return bool|null
     */
    public function getDomicileAvailable(): ?bool
    {
        return $this->container['domicile_available'];
    }

    /**
     * Sets domicile_available
     *
     * @param bool|null $domicile_available domicile_available
     *
     * @return $this
     */
    public function setDomicileAvailable(?bool $domicile_available): static
    {
        if (is_null($domicile_available)) {
            throw new InvalidArgumentException('non-nullable domicile_available cannot be null');
        }
        $this->container['domicile_available'] = $domicile_available;

        return $this;
    }

    /**
     * Gets is_auth_code_available
     *
     * @return bool|null
     */
    public function getIsAuthCodeAvailable(): ?bool
    {
        return $this->container['is_auth_code_available'];
    }

    /**
     * Sets is_auth_code_available
     *
     * @param bool|null $is_auth_code_available is_auth_code_available
     *
     * @return $this
     */
    public function setIsAuthCodeAvailable(?bool $is_auth_code_available): static
    {
        if (is_null($is_auth_code_available)) {
            throw new InvalidArgumentException('non-nullable is_auth_code_available cannot be null');
        }
        $this->container['is_auth_code_available'] = $is_auth_code_available;

        return $this;
    }

    /**
     * Gets is_auth_code_changeable
     *
     * @return bool|null
     */
    public function getIsAuthCodeChangeable(): ?bool
    {
        return $this->container['is_auth_code_changeable'];
    }

    /**
     * Sets is_auth_code_changeable
     *
     * @param bool|null $is_auth_code_changeable is_auth_code_changeable
     *
     * @return $this
     */
    public function setIsAuthCodeChangeable(?bool $is_auth_code_changeable): static
    {
        if (is_null($is_auth_code_changeable)) {
            throw new InvalidArgumentException('non-nullable is_auth_code_changeable cannot be null');
        }
        $this->container['is_auth_code_changeable'] = $is_auth_code_changeable;

        return $this;
    }

    /**
     * Gets is_auth_code_requested
     *
     * @return bool|null
     */
    public function getIsAuthCodeRequested(): ?bool
    {
        return $this->container['is_auth_code_requested'];
    }

    /**
     * Sets is_auth_code_requested
     *
     * @param bool|null $is_auth_code_requested is_auth_code_requested
     *
     * @return $this
     */
    public function setIsAuthCodeRequested(?bool $is_auth_code_requested): static
    {
        if (is_null($is_auth_code_requested)) {
            throw new InvalidArgumentException('non-nullable is_auth_code_requested cannot be null');
        }
        $this->container['is_auth_code_requested'] = $is_auth_code_requested;

        return $this;
    }

    /**
     * Gets is_private_whois_allowed
     *
     * @return bool|null
     */
    public function getIsPrivateWhoisAllowed(): ?bool
    {
        return $this->container['is_private_whois_allowed'];
    }

    /**
     * Sets is_private_whois_allowed
     *
     * @param bool|null $is_private_whois_allowed is_private_whois_allowed
     *
     * @return $this
     */
    public function setIsPrivateWhoisAllowed(?bool $is_private_whois_allowed): static
    {
        if (is_null($is_private_whois_allowed)) {
            throw new InvalidArgumentException('non-nullable is_private_whois_allowed cannot be null');
        }
        $this->container['is_private_whois_allowed'] = $is_private_whois_allowed;

        return $this;
    }

    /**
     * Gets is_trade_auth_code_required
     *
     * @return string|null
     */
    public function getIsTradeAuthCodeRequired(): ?string
    {
        return $this->container['is_trade_auth_code_required'];
    }

    /**
     * Sets is_trade_auth_code_required
     *
     * @param string|null $is_trade_auth_code_required is_trade_auth_code_required
     *
     * @return $this
     */
    public function setIsTradeAuthCodeRequired(?string $is_trade_auth_code_required): static
    {
        if (is_null($is_trade_auth_code_required)) {
            throw new InvalidArgumentException('non-nullable is_trade_auth_code_required cannot be null');
        }
        $this->container['is_trade_auth_code_required'] = $is_trade_auth_code_required;

        return $this;
    }

    /**
     * Gets is_transfer_auth_code_required
     *
     * @return string|null
     */
    public function getIsTransferAuthCodeRequired(): ?string
    {
        return $this->container['is_transfer_auth_code_required'];
    }

    /**
     * Sets is_transfer_auth_code_required
     *
     * @param string|null $is_transfer_auth_code_required is_transfer_auth_code_required
     *
     * @return $this
     */
    public function setIsTransferAuthCodeRequired(?string $is_transfer_auth_code_required): static
    {
        if (is_null($is_transfer_auth_code_required)) {
            throw new InvalidArgumentException('non-nullable is_transfer_auth_code_required cannot be null');
        }
        $this->container['is_transfer_auth_code_required'] = $is_transfer_auth_code_required;

        return $this;
    }

    /**
     * Gets level_prices
     *
     * @return \Layer7\Openprovider\Model\TldLevelPrice[]|null
     */
    public function getLevelPrices(): ?array
    {
        return $this->container['level_prices'];
    }

    /**
     * Sets level_prices
     *
     * @param \Layer7\Openprovider\Model\TldLevelPrice[]|null $level_prices level_prices
     *
     * @return $this
     */
    public function setLevelPrices(?array $level_prices): static
    {
        if (is_null($level_prices)) {
            throw new InvalidArgumentException('non-nullable level_prices cannot be null');
        }
        $this->container['level_prices'] = $level_prices;

        return $this;
    }

    /**
     * Gets max_period
     *
     * @return int|null
     */
    public function getMaxPeriod(): ?int
    {
        return $this->container['max_period'];
    }

    /**
     * Sets max_period
     *
     * @param int|null $max_period max_period
     *
     * @return $this
     */
    public function setMaxPeriod(?int $max_period): static
    {
        if (is_null($max_period)) {
            throw new InvalidArgumentException('non-nullable max_period cannot be null');
        }
        $this->container['max_period'] = $max_period;

        return $this;
    }

    /**
     * Gets min_period
     *
     * @return int|null
     */
    public function getMinPeriod(): ?int
    {
        return $this->container['min_period'];
    }

    /**
     * Sets min_period
     *
     * @param int|null $min_period min_period
     *
     * @return $this
     */
    public function setMinPeriod(?int $min_period): static
    {
        if (is_null($min_period)) {
            throw new InvalidArgumentException('non-nullable min_period cannot be null');
        }
        $this->container['min_period'] = $min_period;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return $this
     */
    public function setName(?string $name): static
    {
        if (is_null($name)) {
            throw new InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets owner_handle_supported
     *
     * @return bool|null
     */
    public function getOwnerHandleSupported(): ?bool
    {
        return $this->container['owner_handle_supported'];
    }

    /**
     * Sets owner_handle_supported
     *
     * @param bool|null $owner_handle_supported owner_handle_supported
     *
     * @return $this
     */
    public function setOwnerHandleSupported(?bool $owner_handle_supported): static
    {
        if (is_null($owner_handle_supported)) {
            throw new InvalidArgumentException('non-nullable owner_handle_supported cannot be null');
        }
        $this->container['owner_handle_supported'] = $owner_handle_supported;

        return $this;
    }

    /**
     * Gets prices
     *
     * @return \Layer7\Openprovider\Model\TldPrices|null
     */
    public function getPrices(): ?\Layer7\Openprovider\Model\TldPrices
    {
        return $this->container['prices'];
    }

    /**
     * Sets prices
     *
     * @param \Layer7\Openprovider\Model\TldPrices|null $prices prices
     *
     * @return $this
     */
    public function setPrices(?\Layer7\Openprovider\Model\TldPrices $prices): static
    {
        if (is_null($prices)) {
            throw new InvalidArgumentException('non-nullable prices cannot be null');
        }
        $this->container['prices'] = $prices;

        return $this;
    }

    /**
     * Gets quarantine_period
     *
     * @return int|null
     */
    public function getQuarantinePeriod(): ?int
    {
        return $this->container['quarantine_period'];
    }

    /**
     * Sets quarantine_period
     *
     * @param int|null $quarantine_period quarantine_period
     *
     * @return $this
     */
    public function setQuarantinePeriod(?int $quarantine_period): static
    {
        if (is_null($quarantine_period)) {
            throw new InvalidArgumentException('non-nullable quarantine_period cannot be null');
        }
        $this->container['quarantine_period'] = $quarantine_period;

        return $this;
    }

    /**
     * Gets reseller_handle_enabled
     *
     * @return bool|null
     */
    public function getResellerHandleEnabled(): ?bool
    {
        return $this->container['reseller_handle_enabled'];
    }

    /**
     * Sets reseller_handle_enabled
     *
     * @param bool|null $reseller_handle_enabled reseller_handle_enabled
     *
     * @return $this
     */
    public function setResellerHandleEnabled(?bool $reseller_handle_enabled): static
    {
        if (is_null($reseller_handle_enabled)) {
            throw new InvalidArgumentException('non-nullable reseller_handle_enabled cannot be null');
        }
        $this->container['reseller_handle_enabled'] = $reseller_handle_enabled;

        return $this;
    }

    /**
     * Gets reseller_handle_supported
     *
     * @return bool|null
     */
    public function getResellerHandleSupported(): ?bool
    {
        return $this->container['reseller_handle_supported'];
    }

    /**
     * Sets reseller_handle_supported
     *
     * @param bool|null $reseller_handle_supported reseller_handle_supported
     *
     * @return $this
     */
    public function setResellerHandleSupported(?bool $reseller_handle_supported): static
    {
        if (is_null($reseller_handle_supported)) {
            throw new InvalidArgumentException('non-nullable reseller_handle_supported cannot be null');
        }
        $this->container['reseller_handle_supported'] = $reseller_handle_supported;

        return $this;
    }

    /**
     * Gets restrictions
     *
     * @return string[]|null
     */
    public function getRestrictions(): ?array
    {
        return $this->container['restrictions'];
    }

    /**
     * Sets restrictions
     *
     * @param string[]|null $restrictions restrictions
     *
     * @return $this
     */
    public function setRestrictions(?array $restrictions): static
    {
        if (is_null($restrictions)) {
            throw new InvalidArgumentException('non-nullable restrictions cannot be null');
        }
        $this->container['restrictions'] = $restrictions;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus(): ?string
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return $this
     */
    public function setStatus(?string $status): static
    {
        if (is_null($status)) {
            throw new InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets supported_application_mode
     *
     * @return \Layer7\Openprovider\Model\TldApplicationMode[]|null
     */
    public function getSupportedApplicationMode(): ?array
    {
        return $this->container['supported_application_mode'];
    }

    /**
     * Sets supported_application_mode
     *
     * @param \Layer7\Openprovider\Model\TldApplicationMode[]|null $supported_application_mode supported_application_mode
     *
     * @return $this
     */
    public function setSupportedApplicationMode(?array $supported_application_mode): static
    {
        if (is_null($supported_application_mode)) {
            throw new InvalidArgumentException('non-nullable supported_application_mode cannot be null');
        }
        $this->container['supported_application_mode'] = $supported_application_mode;

        return $this;
    }

    /**
     * Gets supported_idn_scripts
     *
     * @return \Layer7\Openprovider\Model\TldIdnScript[]|null
     */
    public function getSupportedIdnScripts(): ?array
    {
        return $this->container['supported_idn_scripts'];
    }

    /**
     * Sets supported_idn_scripts
     *
     * @param \Layer7\Openprovider\Model\TldIdnScript[]|null $supported_idn_scripts supported_idn_scripts
     *
     * @return $this
     */
    public function setSupportedIdnScripts(?array $supported_idn_scripts): static
    {
        if (is_null($supported_idn_scripts)) {
            throw new InvalidArgumentException('non-nullable supported_idn_scripts cannot be null');
        }
        $this->container['supported_idn_scripts'] = $supported_idn_scripts;

        return $this;
    }

    /**
     * Gets tech_handle_supported
     *
     * @return bool|null
     */
    public function getTechHandleSupported(): ?bool
    {
        return $this->container['tech_handle_supported'];
    }

    /**
     * Sets tech_handle_supported
     *
     * @param bool|null $tech_handle_supported tech_handle_supported
     *
     * @return $this
     */
    public function setTechHandleSupported(?bool $tech_handle_supported): static
    {
        if (is_null($tech_handle_supported)) {
            throw new InvalidArgumentException('non-nullable tech_handle_supported cannot be null');
        }
        $this->container['tech_handle_supported'] = $tech_handle_supported;

        return $this;
    }

    /**
     * Gets trade_available
     *
     * @return bool|null
     */
    public function getTradeAvailable(): ?bool
    {
        return $this->container['trade_available'];
    }

    /**
     * Sets trade_available
     *
     * @param bool|null $trade_available trade_available
     *
     * @return $this
     */
    public function setTradeAvailable(?bool $trade_available): static
    {
        if (is_null($trade_available)) {
            throw new InvalidArgumentException('non-nullable trade_available cannot be null');
        }
        $this->container['trade_available'] = $trade_available;

        return $this;
    }

    /**
     * Gets transfer_available
     *
     * @return bool|null
     */
    public function getTransferAvailable(): ?bool
    {
        return $this->container['transfer_available'];
    }

    /**
     * Sets transfer_available
     *
     * @param bool|null $transfer_available transfer_available
     *
     * @return $this
     */
    public function setTransferAvailable(?bool $transfer_available): static
    {
        if (is_null($transfer_available)) {
            throw new InvalidArgumentException('non-nullable transfer_available cannot be null');
        }
        $this->container['transfer_available'] = $transfer_available;

        return $this;
    }

    /**
     * Gets usage_count
     *
     * @return int|null
     */
    public function getUsageCount(): ?int
    {
        return $this->container['usage_count'];
    }

    /**
     * Sets usage_count
     *
     * @param int|null $usage_count usage_count
     *
     * @return $this
     */
    public function setUsageCount(?int $usage_count): static
    {
        if (is_null($usage_count)) {
            throw new InvalidArgumentException('non-nullable usage_count cannot be null');
        }
        $this->container['usage_count'] = $usage_count;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[ReturnTypeWillChange]
    public function offsetGet(mixed $offset): mixed
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet(mixed $offset, mixed $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[ReturnTypeWillChange]
    public function jsonSerialize(): mixed
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString(): string
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue(): string
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


