name: Update OpenProvider REST Client

on:
  schedule:
    - cron: "0 0 * * 1" # Runs weekly on Monday at midnight
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  generate-client:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate REST Client Using Docker
        run: |
          docker run --rm -v "${PWD}:/local" openapitools/openapi-generator-cli generate \
            -i https://raw.githubusercontent.com/openprovider/api-documentation/master/swagger.json \
            -g phpnext \
            -o /local/generated-client \
            --additional-properties=invokerPackage=Layer7\\Openprovider,packageName=openprovider-rest

      - name: Update Repository with Generated Code
        run: |
          rm -rf src/
          cp -r generated-client/src/ src/
          cp generated-client/composer.json composer.json

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update OpenProvider REST Client"
          git push